#!/bin/bash
# Build a Zephyr app from this repo against the nRF Connect SDK.
#
# Usage:  ./build.sh [app-name] [board]
#
# The SDK is looked for at C:/ncs/v3.4.0 on Windows and ~/ncs/v3.4.0 on Linux
# and macOS. Set NCS_WORKSPACE to use one installed anywhere else:
#
#   NCS_WORKSPACE=/path/to/ncs/v3.4.0 ./build.sh
#
# Why the sources are staged beside the SDK: west computes the source directory
# relative to the workspace, and on Windows a relative path cannot cross drive
# letters, so a repo on a different drive from the SDK fails before anything is
# built. Copying the sources next to the SDK works on every setup, and the
# canonical source stays here in git.
set -e

APP="${1:-switch2_ll}"
BOARD="${2:-promicro_nrf52840/nrf52840/uf2}"
NCS_VER="v3.4.0"

case "$(uname -s)" in
MINGW* | MSYS* | CYGWIN*) DEFAULT_WORKSPACE="C:/ncs/${NCS_VER}" ;;
*) DEFAULT_WORKSPACE="${HOME}/ncs/${NCS_VER}" ;;
esac
WORKSPACE="${NCS_WORKSPACE:-$DEFAULT_WORKSPACE}"

REPO_APP="$(cd "$(dirname "$0")" && pwd)/${APP}"
STAGE="$(dirname "$WORKSPACE")/pair-raught/${APP}"

if [ ! -d "$REPO_APP" ]; then
	echo "no such app: $REPO_APP" >&2
	exit 1
fi

# Check for the SDK and the tools before touching anything, so whatever is
# missing is named up front rather than surfacing halfway through a build.
if [ ! -d "${WORKSPACE}/zephyr" ]; then
	echo "nRF Connect SDK ${NCS_VER} not found at: ${WORKSPACE}" >&2
	echo "install it there, or set NCS_WORKSPACE to where it is" >&2
	exit 1
fi
for tool in nrfutil xxd; do
	if ! command -v "$tool" >/dev/null 2>&1; then
		echo "required tool not found on PATH: $tool" >&2
		exit 1
	fi
done

# Embed the config page as a C array.
#
# The page ships INSIDE the firmware, served by the synthesised USB volume in
# puck_webdisk.c, so it is regenerated here on every build -- a checked-in copy
# would eventually be a page that disagrees with the firmware behind it, which
# is the one failure this whole arrangement exists to prevent.
HTML="$(dirname "$0")/config/raught.html"
GEN="${REPO_APP}/src/raught_html.h"
if [ -f "$HTML" ]; then
	{
		echo "/* GENERATED by build.sh from config/raught.html. Do not edit. */"
		echo "#ifndef RAUGHT_HTML_H"
		echo "#define RAUGHT_HTML_H"
		echo
		echo "#include <stdint.h>"
		echo
		echo "static const uint8_t RAUGHT_HTML[] = {"
		xxd -i < "$HTML"
		echo "};"
		echo
		echo "#define RAUGHT_HTML_LEN ((uint32_t)sizeof RAUGHT_HTML)"
		echo
		echo "#endif /* RAUGHT_HTML_H */"
	} > "$GEN"
	echo "embedded $(wc -c < "$HTML") bytes of raught.html"
fi

mkdir -p "$(dirname "$STAGE")"
rm -rf "$STAGE"
mkdir -p "$STAGE"
# Copy sources only; the build directory stays beside the SDK and is never
# copied back.
cp -r "$REPO_APP"/CMakeLists.txt "$REPO_APP"/prj.conf "$STAGE"/ 2>/dev/null || true
[ -f "$REPO_APP/app.overlay" ] && cp "$REPO_APP/app.overlay" "$STAGE"/
[ -d "$REPO_APP/src" ] && cp -r "$REPO_APP/src" "$STAGE"/
[ -d "$REPO_APP/boards" ] && cp -r "$REPO_APP/boards" "$STAGE"/

echo "building $APP for $BOARD against $WORKSPACE"
nrfutil toolchain-manager launch --ncs-version "$NCS_VER" --chdir "$WORKSPACE" -- \
	west build -b "$BOARD" -p always -d "${STAGE}/build" "$STAGE"

# sysbuild nests each image under build/<app>/, so the UF2 is one level deeper
# than a classic (non-sysbuild) Zephyr build would put it.
UF2="$(find "${STAGE}/build" -name zephyr.uf2 2>/dev/null | head -1)"
if [ -n "$UF2" ] && [ -f "$UF2" ]; then
	cp "$UF2" "${REPO_APP}/${APP}.uf2"
	echo
	echo "UF2 -> ${REPO_APP}/${APP}.uf2"
	echo "size: $(( $(wc -c < "$UF2") / 1024 ))K"
else
	echo "BUILD PRODUCED NO UF2: check the log above" >&2
	exit 1
fi

# The serial-DFU package, built from the SAME hex as the UF2 above.
#
# Both exist because the two bootloader modes take different things: `b` on the
# puck console mounts a drive that takes the .uf2, while a board sitting in
# serial DFU takes this .zip through adafruit-nrfutil. Generating it here rather
# than by hand is what stops it going stale, which it did: a package built
# before a redaction still carried the value that had just been removed.
HEX="$(find "${STAGE}/build" -name zephyr.hex 2>/dev/null | head -1)"
if [ -n "$HEX" ] && command -v adafruit-nrfutil >/dev/null 2>&1; then
	rm -f "${REPO_APP}/${APP}.zip"
	adafruit-nrfutil dfu genpkg --dev-type 0x0052 \
		--application "$HEX" "${REPO_APP}/${APP}.zip" >/dev/null
	echo "DFU -> ${REPO_APP}/${APP}.zip"
elif [ -n "$HEX" ]; then
	rm -f "${REPO_APP}/${APP}.zip"
	echo "note: adafruit-nrfutil not found, no serial-DFU package built"
	echo "      (any stale one has been removed rather than left to mislead)"
fi
